name: .NET Core

on:
  push:
  pull_request:
    branches: [ master, develop ]
jobs:
   job_NET:
      runs-on: ubuntu-latest
      strategy:
          matrix:
            dotnet: [ '3.1.301' ]
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core ${{matrix.dotnet}} build
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.dotnet}}
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal

 
