
name: Angular CLI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-lates
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -prefix ArchitectureProject.ClientApp/
    - run: npm run build --prod -prefix ArchitectureProject.ClientApp/
